---
- name: install kitty pre-built binaries
  ansible.builtin.shell: >
    curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin

- name: Ensure the fonts directory exists
  ansible.builtin.file:
    path: ~/.local/share/fonts
    state: directory

- name: Decrypt the tar.gz.gpg file
  command: >
    gpg --batch --yes --passphrase "{{ font_passwd }}" -o ~/.local/share/fonts/comic-code.tar.gz -d roles/kitty/files/comic-code.tar.gz.gpg
  register: decrypt_result
  changed_when: decrypt_result.rc == 0

- name: Untar the decrypted file into the fonts directory
  unarchive:
    src: ~/.local/share/fonts/comic-code.tar.gz
    dest: ~/.local/share/fonts
  when: decrypt_result.changed

- name: copy kitty config directory if different
  ansible.builtin.copy:
    src: kitty/
    dest: ~/.config/kitty/
    backup: yes
