version: '3'
services:
  ubuntu_server:
    image: ubuntu:latest
    container_name: ansible-test-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2222:22"
    environment:
      - DEBIAN_FRONTEND=noninteractive
    tty: true
