---
- name: install kitty pre-built binaries
  ansible.builtin.shell: >
    curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
  args:
    creates: ~/.local/kitty.app/bin/kitty

- name: copy kitty config directory if different
  ansible.builtin.copy:
    src: kitty/
    dest: ~/.config/kitty/
    backup: yes
