---
- name: install zathura
  ansible.builtin.apt:
    name: zathura
    state: present
  become: true

- name: copy zathura config directory if different
  ansible.builtin.copy:
    src: zathura/
    dest: ~/.config/zathura/
    backup: yes
