---
- name: update apt cache
  apt:
    update_cache: yes
  become: true

- name: update package
  apt:
    upgrade: dist
  become: true
  register: upgrade
  ignore_errors: true

- name: Fix broken dependencies if dist upgrade failed
  command: apt --fix-broken install
  when: upgrade is failed
  become: true
