name: Setup WireGuard

on:
  workflow_dispatch:

jobs:
  setup-wireguard:
    runs-on: ubuntu-latest
    steps:
      - name: Create WireGuard config
        run: |
          sudo mkdir -p /etc/wireguard
          sudo tee /etc/wireguard/wg0.conf > /dev/null <<EOF
          [Interface]
          PrivateKey = ${{ secrets.WIREGUARD_PRIVATE_KEY }}
          Address = 10.0.0.4/32
          MTU = 1420
          DNS = 192.168.0.12

          [Peer]
          PublicKey = v/M0zEAqKvFyeeg6wLSV0m4Nu51I/zL+fym3PVgv4D4=
          AllowedIPs = 0.0.0.0/0
          Endpoint = ${{ secrets.WIREGUARD_ENDPOINT }}
          PersistentKeepalive = 21
          EOF

      - name: Install WireGuard
        run: |
          sudo apt-get install -y wireguard

      - name: Bring up WireGuard interface
        run: sudo wg-quick up wg0

      - name: Test DNS & connectivity
        run: |
          curl -v --max-time 10 http://nginx.homelab.int || true
