name: Setup WireGuard

on:
  push:
  workflow_dispatch:

jobs:
  setup-wireguard:
    runs-on: ubuntu-latest
    steps:
      - name: update apt cache
        run: sudo apt update

      - name: install wireguard package
        run: sudo apt install -y wireguard

      - name: clean up previous wg0 interface
        run: |
          sudo ip link set wg0 down 2>/dev/null || true
          sudo ip link delete dev wg0 2>/dev/null || true

      - name: configure and bring up wireguard interface
        run: |
          echo "${{ secrets.WIREGUARD_PRIVATE_KEY }}" > privatekey
          sudo ip link add dev wg0 type wireguard
          sudo ip address add dev wg0 10.0.0.4/24
          sudo wg set wg0 listen-port 48123 private-key privatekey peer v/M0zEAqKvFyeeg6wLSV0m4Nu51I/zL+fym3PVgv4D4= allowed-ips 0.0.0.0/0 endpoint ${{ secrets.WIREGUARD_ENDPOINT }}
          sudo ip link set dev wg0 mtu 1420
          sudo ip link set up dev wg0
          sudo ip route add 192.168.0.0/24 dev wg0

      - name: test connectivity to internal ip
        run: ping -c4 192.168.0.1
